# Generated by Django 5.2.5 on 2025-11-19 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_contactocolegio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionmensajeria',
            options={'verbose_name': 'Configuración de Mensajería', 'verbose_name_plural': 'Configuraciones de Mensajería'},
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='mensajeria__usuario_92775b_idx',
            old_name='ratelimit_usuario_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='mensajeria__ip_addr_1f122b_idx',
            old_name='ratelimit_ip_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
