# Generated by Django 5.2.5 on 2025-11-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_alter_configuracionmensajeria_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
    ]
