# Generated by Django 5.2.5 on 2025-12-10 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de Sesión"),
                            ("nota", "Registro de Notas"),
                            ("asistencia", "Registro de Asistencia"),
                            ("recurso", "Recurso Académico"),
                            ("anotacion", "Anotación/Hoja de Vida"),
                            ("usuario", "Gestión de Usuarios"),
                            ("curso", "Gestión de Cursos"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Descripción breve de la acción", max_length=255
                    ),
                ),
                (
                    "detalles",
                    models.TextField(blank=True, help_text="Detalles técnicos o JSON"),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Actividad",
                "verbose_name_plural": "Registros de Actividad",
                "ordering": ["-fecha"],
            },
        ),
    ]
