# Generated by Django 5.2.5 on 2025-11-06 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icono', models.CharField(default='bi-file-earmark', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ponderacion_por_defecto', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Examen',
                'verbose_name_plural': 'Tipos de Exámenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoPadres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normal', max_length=15)),
                ('dirigido_a', models.CharField(default='todos', help_text='todos, padres, apoderados, estudiantes', max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('leido_count', models.PositiveIntegerField(default=0)),
                ('cursos_objetivo', models.ManyToManyField(blank=True, related_name='comunicados', to='academico.curso')),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado a Padres',
                'verbose_name_plural': 'Comunicados a Padres',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('xls', 'Excel'), ('ppt', 'PowerPoint'), ('img', 'Imagen'), ('zip', 'Archivo comprimido')], default='pdf', max_length=10)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('solo_estudiantes', 'Solo Estudiantes'), ('solo_profesores', 'Solo Profesores'), ('solo_administrativos', 'Solo Administrativos')], default='publico', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Separados por comas', max_length=200)),
                ('tamaño', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('descargar_count', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('es_oficial', models.BooleanField(default=False, help_text='Documento oficial del establecimiento')),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.categoriadocumento')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_periodo', models.CharField(choices=[('semestral', 'Semestral'), ('trimestral', 'Trimestral'), ('mensual', 'Mensual'), ('prueba', 'Prueba')], default='prueba', max_length=15)),
                ('fecha_aplicacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('instrucciones', models.TextField(blank=True)),
                ('material_permitido', models.TextField(blank=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='documentos.tipoexamen')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['fecha_aplicacion', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDescargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga',
                'verbose_name_plural': 'Descargas',
                'ordering': ['-fecha_descarga'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo_pregunta', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('desarrollo', 'Desarrollo'), ('completar', 'Completar')], max_length=20)),
                ('enunciado', models.TextField()),
                ('opciones', models.TextField(blank=True, help_text='Para preguntas de opción múltiple (separadas por |)')),
                ('respuesta_correcta', models.TextField(blank=True)),
                ('puntos', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='documentos.examen')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Exámenes',
                'ordering': ['orden', 'numero'],
                'unique_together': {('examen', 'numero')},
            },
        ),
    ]
