# Generated by Django 5.2.5 on 2025-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('bajada', models.CharField(blank=True, max_length=200, verbose_name='Resumen')),
                ('cuerpo', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('es_publica', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
