# Generated by Django 5.2.5 on 2025-11-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-destacado', '-urgente', '-creado']},
        ),
        migrations.AddField(
            model_name='noticia',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('académico', 'Académico'), ('actividades', 'Actividades'), ('convivencia', 'Convivencia Escolar'), ('eventos', 'Eventos'), ('deportes', 'Deportes'), ('cultura', 'Cultura'), ('administrativo', 'Administrativo'), ('comunicado', 'Comunicado')], default='académico', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
