# Generated by Django 5.2.5 on 2025-11-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_categorianoticia_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('académico', 'Académico'), ('actividades', 'Actividades'), ('convivencia', 'Convivencia Escolar'), ('eventos', 'Eventos'), ('deportes', 'Deportes'), ('cultura', 'Cultura'), ('administrativo', 'Administrativo'), ('comunicado', 'Comunicado'), ('consejo', 'Consejo de Profesores')], default='académico', max_length=20),
        ),
    ]
