# Generated by Django 6.0 on 2025-12-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0003_alter_noticia_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='requiere_confirmacion',
            field=models.BooleanField(default=False, help_text='Si está activo, los usuarios deben confirmar que leyeron este comunicado'),
        ),
        migrations.CreateModel(
            name='ConfirmacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='comunicacion.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_confirmadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmación de Lectura',
                'verbose_name_plural': 'Confirmaciones de Lectura',
                'ordering': ['-fecha_confirmacion'],
                'unique_together': {('noticia', 'usuario')},
            },
        ),
    ]
