# Generated by Django 5.2.5 on 2025-11-25 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_calificacion_numero_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ponderacion_por_defecto', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Examen',
                'verbose_name_plural': 'Tipos de Exámenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_periodo', models.CharField(choices=[('semestral', 'Semestral'), ('trimestral', 'Trimestral'), ('mensual', 'Mensual'), ('prueba', 'Prueba')], default='prueba', max_length=15)),
                ('fecha_aplicacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('instrucciones', models.TextField(blank=True)),
                ('material_permitido', models.TextField(blank=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.tipoexamen')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['fecha_aplicacion', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo_pregunta', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('desarrollo', 'Desarrollo'), ('completar', 'Completar')], max_length=20)),
                ('enunciado', models.TextField()),
                ('opciones', models.TextField(blank=True, help_text='Para preguntas de opción múltiple (separadas por |)')),
                ('respuesta_correcta', models.TextField(blank=True)),
                ('puntos', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academico.examen')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Exámenes',
                'ordering': ['orden', 'numero'],
                'unique_together': {('examen', 'numero')},
            },
        ),
    ]
