# Generated by Django 5.2.5 on 2025-11-26 07:24

import academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_tipoexamen_examen_preguntaexamen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha_evaluacion'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nivel', 'letra'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='horarioclases',
            options={'ordering': ['dia', 'hora'], 'verbose_name': 'Horario de Clases', 'verbose_name_plural': 'Horarios de Clases'},
        ),
        migrations.AlterModelOptions(
            name='inscripcioncurso',
            options={'ordering': ['curso__nivel', 'curso__letra'], 'verbose_name': 'Inscripción de Curso', 'verbose_name_plural': 'Inscripciones de Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='año',
            field=models.IntegerField(default=academico.models.obtener_año_actual),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='año',
            field=models.IntegerField(default=academico.models.obtener_año_actual),
        ),
    ]
