# Generated by Django 5.2.5 on 2025-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_asignatura_options_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncurso',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Promedio calculado automáticamente', max_digits=4, null=True),
        ),
    ]
