# Generated by Django 5.2.5 on 2025-11-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_inscripcioncurso_promedio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario__in': ['profesor', 'administrativo', 'directivo']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario__in': ['profesor', 'administrativo', 'directivo']}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__tipo_usuario__in': ['profesor', 'administrativo', 'directivo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examen',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario__in': ['profesor', 'administrativo', 'directivo']}, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarioclases',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario__in': ['profesor', 'administrativo', 'directivo']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
