# Generated by Django 5.2.5 on 2025-12-10 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0006_alter_asistencia_estudiante_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("positiva", "Positiva (Mérito)"),
                            ("negativa", "Negativa (Falta)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("responsabilidad", "Responsabilidad"),
                            ("respeto", "Respeto y Convivencia"),
                            ("presentacion", "Presentación Personal"),
                            ("participacion", "Participación en Clases"),
                            ("honradez", "Honradez"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observación")),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"perfil__tipo_usuario": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        limit_choices_to={
                            "perfil__tipo_usuario__in": [
                                "profesor",
                                "administrativo",
                                "directivo",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anotación",
                "verbose_name_plural": "Anotaciones",
                "ordering": ["-fecha"],
            },
        ),
    ]
