# Generated by Django 5.2.5 on 2025-12-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0007_anotacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("archivo", models.FileField(upload_to="recursos_academicos/%Y/%m/")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.asignatura",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="academico.curso",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        limit_choices_to={
                            "perfil__tipo_usuario__in": [
                                "profesor",
                                "administrativo",
                                "directivo",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso Académico",
                "verbose_name_plural": "Recursos Académicos",
                "ordering": ["-creado"],
            },
        ),
    ]
