# Generated by Django 6.0 on 2025-12-15 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_recursoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(decimal_places=2, help_text='Nota del 1.0 al 7.0', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0, message='La nota mínima es 1.0'), django.core.validators.MaxValueValidator(7.0, message='La nota máxima es 7.0')]),
        ),
    ]
