# Generated by Django 5.2.5 on 2025-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_actual', models.PositiveIntegerField(default=2024, verbose_name='Año Escolar Actual')),
                ('semestre_actual', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Configuración Académica',
                'verbose_name_plural': 'Configuración Académica',
            },
        ),
    ]
