# Generated by Django 6.0 on 2025-12-18 00:52
# Modified to support existing data

import uuid as uuid_lib
from django.db import migrations, models


def generate_uuids_for_existing(apps, schema_editor):
    """Genera UUIDs para registros existentes"""
    Notificacion = apps.get_model('core', 'Notificacion')
    for obj in Notificacion.objects.filter(uuid__isnull=True):
        obj.uuid = uuid_lib.uuid4()
        obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificacion'),
    ]

    operations = [
        # Paso 1: Agregar campo sin unique
        migrations.AddField(
            model_name='notificacion',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        # Paso 2: Generar UUIDs para registros existentes
        migrations.RunPython(generate_uuids_for_existing, migrations.RunPython.noop),
        # Paso 3: Hacer campo unique y not null
        migrations.AlterField(
            model_name='notificacion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False, unique=True),
        ),
    ]
