# Generated by Django 6.0 on 2025-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificacion_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del colegio (ej: COLE-A1B2)', max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Colegio')),
                ('url', models.URLField(blank=True, help_text='URL pública del colegio (ej: https://colegio.schoolar.cl)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegio/')),
                ('color_primario', models.CharField(default='#1976D2', help_text='Color HEX', max_length=7)),
                ('color_secundario', models.CharField(default='#424242', help_text='Color HEX', max_length=7)),
                ('registrado_en_directorio', models.BooleanField(default=False, help_text='True si el colegio ya se registró con el Directorio Central')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Colegio',
                'verbose_name_plural': 'Configuración del Colegio',
            },
        ),
    ]
