# Generated by Django 6.0 on 2025-12-15 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0009_alter_calificacion_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('trabajo', 'Trabajo de Investigación'), ('proyecto', 'Proyecto'), ('lectura', 'Lectura'), ('ejercicio', 'Ejercicios')], default='tarea', max_length=20)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('hora_limite', models.TimeField(blank=True, null=True, verbose_name='Hora Límite')),
                ('puntaje_maximo', models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='Puntaje Máximo')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tareas/adjuntos/', verbose_name='Archivo Adjunto')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='publicada', max_length=20)),
                ('permite_entrega_tardia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tareas/entregas/', verbose_name='Archivo Entregado')),
                ('comentario_estudiante', models.TextField(blank=True, verbose_name='Comentario del Estudiante')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('entrega_tardia', models.BooleanField(default=False)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Puntaje Obtenido')),
                ('comentario_profesor', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('revisada', 'Revisada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada - Rehacer')], default='pendiente', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
