"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR / "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,.onrender.com').split(',')

if DEBUG: ALLOWED_HOSTS.extend(['127.0.0.1', 'localhost'])

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000,https://proyecto-integrado-pagina-web.onrender.com').split(',')

if DEBUG: 
    # Add specific local origins
    CSRF_TRUSTED_ORIGINS.extend([ 
        'http://localhost:8000', 'http://127.0.0.1:8000', 
        'https://localhost:8000', 'https://127.0.0.1:8000',
    ])
    
    # Try to automatically detect local IP
    try:
        import socket
        hostname = socket.gethostname()
        local_ip = socket.gethostbyname(hostname)
        CSRF_TRUSTED_ORIGINS.extend([
            f'http://{local_ip}:8000',
            f'https://{local_ip}:8000',
        ])
    except ImportError:
        # socket module is standard, but safety first
        pass

    # Dynamically trust all ALLOWED_HOSTS (if explicit IPs are defined)
    for host in ALLOWED_HOSTS:
        if '*' in host: continue
        host_clean = host.strip()
        if not host_clean: continue
            
        origins_to_add = [
            f'http://{host_clean}',
            f'https://{host_clean}',
            f'http://{host_clean}:8000',
            f'https://{host_clean}:8000',
        ]
        for origin in origins_to_add:
            if origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(origin)
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
    'comunicacion',
    'usuarios',
    'academico',
    'documentos',
    'talleres',
    'mensajeria',
    'django_htmx',
    'administrativo',
    'tareas',
    'calendario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {
        "context_processors": [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
            "core.context_processors.institucion_info",
        ],
    },
}]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Messages Framework
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Authentication URLs
LOGIN_URL = "/usuarios/login/"
LOGIN_REDIRECT_URL = "/usuarios/panel/"
LOGOUT_REDIRECT_URL = "/usuarios/login/"

# Security Settings (Development)
# Security Settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    # Production Security Hardening
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    
    # Content Security Policy (Basic)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    
    # CSP settings suitable for Bootstrap/Google Fonts
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com")
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
    CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com")
    CSP_IMG_SRC = ("'self'", "data:")
else:
    # Development Settings
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_SSL_REDIRECT = False
     
    # FORCE NEW COOKIES (Fix for stuck CSRF issues)
    CSRF_COOKIE_NAME = "csrftoken_v2"
    SESSION_COOKIE_NAME = "sessionid_v2"
    
    # Relaxed CSP for Dev
    X_FRAME_OPTIONS = "SAMEORIGIN"

# SAFETY NET: If running on localhost/127.0.0.1, FORCE insecure cookies to avoid CSRF issues
# This handles cases where DEBUG might be accidentally False but we are locally testing
import socket
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
except:
    local_ip = ""

# Hardcoded trust for local development to ensure it works
CSRF_TRUSTED_ORIGINS.extend([
    'http://localhost:8000', 
    'http://127.0.0.1:8000',
    'http://0.0.0.0:8000',
])

if 'localhost' in ALLOWED_HOSTS or '127.0.0.1' in ALLOWED_HOSTS or any(ip in str(ALLOWED_HOSTS) for ip in ['192.168.', '10.0.', '172.']):
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

# Email Configuration (for contact form)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

# Institution Information for Context Processor
INSTITUCION_INFO = {
    'nombre': 'Liceo Juan Bautista de Hualqui',
    'direccion': 'Hualqui, Región del Biobío, Chile',
    'telefono': '+56 41 2XXX XXXX',
    'email': 'contacto@liceohualqui.cl',
    'rbd': '12345-6',
    'anno_fundacion': 1985,
}

# Pagination Settings
PAGINACION_POR_PAGINA = 10

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Liceo Juan Bautista",
    "site_header": "Liceo Juan Bautista",
    "site_brand": "Liceo Juan Bautista",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "copyright": "Liceo Juan Bautista de Hualqui",
    "search_model": ["usuarios.User", "academico.Curso"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Sitio", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [
        "auth.User", 
        "auth.Group",
        "academico.InscripcionCurso",
        "academico.HorarioClases",
        "academico.PreguntaExamen",
        "academico.TipoExamen",
        "documentos.HistorialDescargas",
        "mensajeria.Mensaje"
    ],
    "order_with_respect_to": ["usuarios", "academico", "comunicacion", "mensajeria"],
    "icons": {
        "auth": "fas fa-users-cog",
        "usuarios.User": "fas fa-user",
        "usuarios.PerfilUsuario": "fas fa-id-card",
        "academico.Curso": "fas fa-chalkboard",
        "academico.Asignatura": "fas fa-book",
        "academico.Calificacion": "fas fa-star",
        "academico.Asistencia": "fas fa-calendar-check",
        "comunicacion.Noticia": "fas fa-newspaper",
        "mensajeria.Mensaje": "fas fa-envelope",
        "academico.Examen": "fas fa-file-alt",
        "academico.TipoExamen": "fas fa-tags",
        "academico.PreguntaExamen": "fas fa-question-circle",
        "core.ConfiguracionSistema": "fas fa-cogs",
        "core.ConfiguracionAcademica": "fas fa-calendar-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

