# Generated by Django 5.2.5 on 2025-11-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_contacto_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
    ]
