# Generated by Django 5.2.5 on 2025-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_configuracionsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='promedio_general',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Promedio general calculado automáticamente', max_digits=4, null=True),
        ),
    ]
