# Generated by Django 6.0 on 2025-12-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('otro', 'Otro Familiar')], default='tutor', max_length=20, verbose_name='Vínculo Familiar')),
                ('es_apoderado_principal', models.BooleanField(default=False, help_text='Marcar si es el apoderado principal del estudiante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(limit_choices_to={'tipo_usuario': 'apoderado'}, on_delete=django.db.models.deletion.CASCADE, related_name='pupilos', to='usuarios.perfilusuario', verbose_name='Apoderado')),
                ('estudiante', models.ForeignKey(limit_choices_to={'tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='usuarios.perfilusuario', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pupilo',
                'verbose_name_plural': 'Pupilos',
                'ordering': ['estudiante__user__last_name'],
                'unique_together': {('apoderado', 'estudiante')},
            },
        ),
    ]
