# Generated by Django 6.0 on 2025-12-18 00:52
# Modified to support existing data

import uuid as uuid_lib
from django.db import migrations, models


def generate_uuids_for_existing(apps, schema_editor):
    """Genera UUIDs para registros existentes"""
    models_to_update = [
        ('usuarios', 'PerfilUsuario'),
        ('usuarios', 'Pupilo'),
    ]
    for app_label, model_name in models_to_update:
        Model = apps.get_model(app_label, model_name)
        for obj in Model.objects.filter(uuid__isnull=True):
            obj.uuid = uuid_lib.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_pupilo'),
    ]

    operations = [
        # Paso 1: Agregar campos sin unique
        migrations.AddField(
            model_name='perfilusuario',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='pupilo',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        # Paso 2: Generar UUIDs para registros existentes
        migrations.RunPython(generate_uuids_for_existing, migrations.RunPython.noop),
        # Paso 3: Hacer campos unique y not null
        migrations.AlterField(
            model_name='perfilusuario',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pupilo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False, unique=True),
        ),
    ]
