# Generated by Django 5.2.5 on 2025-11-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntaExamen',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='TipoExamen',
        ),
    ]
