# Generated by Django 5.2.5 on 2025-11-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_inscripcioncurso_promedio'),
        ('documentos', '0002_remove_examen_asignatura_remove_examen_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Curso al que pertenece el documento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='academico.curso'),
        ),
    ]
