# Generated by Django 6.0 on 2025-12-15 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0009_alter_calificacion_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('festivo', 'Festivo'), ('reunion', 'Reunión'), ('evaluacion', 'Evaluación'), ('feriado', 'Feriado'), ('actividad', 'Actividad Extracurricular'), ('otro', 'Otro')], default='academico', max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('todo_el_dia', models.BooleanField(default=True, verbose_name='Todo el día')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('color', models.CharField(choices=[('#3788d8', 'Azul'), ('#dc3545', 'Rojo'), ('#28a745', 'Verde'), ('#ffc107', 'Amarillo'), ('#6f42c1', 'Morado'), ('#17a2b8', 'Celeste'), ('#6c757d', 'Gris')], default='#3788d8', max_length=10)),
                ('visible_para_todos', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, help_text='Dejar vacío para evento general', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
